remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Bin Guo
description: Assistant Professor at Trent University, Department of Computer Science
show_downloads: true
logo: assets/binguo.jpg
