remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dr. Bin Guo (郭斌) 
description: Assistant Professor at Trent University (binguo[at]trentu.ca); Adjunct Assistant Professor at McMaster University (guob15[at]mcmaster.ca)
show_downloads: true
logo: assets/binguo.jpg
